name: test_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: 3.0.5

dependencies:
  bloc: ^8.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.1
  responsive_sizer: ^3.1.1
  responsive_builder: ^0.4.3
  transparent_image: ^2.0.0
  flutter_svg: ^1.1.5
  intl: ^0.17.0
  simple_animations: ^5.0.0
  visibility_detector: ^0.3.3

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

flutter_gen:
  output: lib/generated/

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/lato/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/lato/Lato-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/lato/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/lato/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/lato/Lato-Medium.ttf
          weight: 500
        - asset: assets/fonts/lato/Lato-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/lato/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/lato/Lato-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/lato/Lato-Black.ttf
          weight: 900
